/*
CRIANDO DW(EXTRACAO_DADOS_SISTEMA) NO DB(MODELO_PREDITIVO) PARA ARMAZENAR OS DADOS 
DA TABELA(CONTRATOS_FINANCIAMENTOS) DO DB(SISTEMA_BANCO)
*/
USE MODELOS_PREDITIVOS
GO

IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'EXTRACAO_DADOS_SISTEMA' AND TYPE = 'U')
	BEGIN
		DROP TABLE EXTRACAO_DADOS_SISTEMA
	END
GO

/*
É UMA BOA PRÁTICA PARA QUE QUEM VAI FAZER A ANÁLISE/MODELO TENHA UM LOGON COM AS DEVIDAS PERMISSÕES DE MANIPULAÇÃO
DE CADA DB E PARA QUE NÃO ALTERE O DB ORIGINAL(QUE É O QUE ESTAMOS SIMULANDO UM SISTEMA DE ERP "SISTEMA_BANCO") 
*/
CREATE TABLE EXTRACAO_DADOS_SISTEMA(
	NUMERO_CONTRATO					INTEGER			NULL,
	DATA_ASSINATURA_CONTRATO		DATE			NULL,
	TIPO_FINANCIAMENTO				VARCHAR(20)		NULL,
	TAXA_AO_ANO						NUMERIC(10,2)	NULL,
	PZ_FINANCIAMENTO				INTEGER			NULL,
	CIDADE_CLIENTE					VARCHAR(40)		NULL,
	ESTADO_CLIENTE					VARCHAR(02)		NULL,
	RENDA_MENSAL_CLIENTE			NUMERIC(10,2)	NULL,
	QT_PC_ATRASO					INTEGER			NULL,
	QT_DIAS_PRIM_PC_ATRASO			INTEGER			NULL,
	QT_TOTAL_PC_PAGAS				INTEGER			NULL,
	VL_TOTAL_PC_PAGAS				NUMERIC(10,2)	NULL,
	QT_PC_PAGA_EM_DIA				INTEGER			NULL,
	QT_DIAS_MIN_ATRASO				INTEGER			NULL,
	QT_DIAS_MAX_ATRASO				INTEGER			NULL,
	QT_DIAS_MEDIA_ATRASO			INTEGER			NULL,
	VALOR_FINANCIAMENTO				NUMERIC(12,2)	NULL,
	VALOR_PARCELA					NUMERIC(12,2)	NULL,
	IDADE_DATA_ASSINATURA_CONTRATO	INTEGER			NULL,
	INADIMPLENTE_COBRANCA			VARCHAR(03)		NULL) 
GO
-- AGORA NO ARQUIVO PROCEDURE.SQL VOU FAZER UMA PROCEDURE PRA EXTRAÇÃO AUTOMÁTICA DOS DADOS  


