-- CRIA��O DA PROCEDURE DE EXTRA��O AUTOM�TICA DOS DADOS DO BANCO ERP PARA A BASE DO MODELO
USE MODELOS_PREDITIVOS
GO

IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'SP_EXTRAI_DADOS_SISTEMA_ERP' AND TYPE = 'P')
	BEGIN
		DROP PROCEDURE SP_EXTRAI_DADOS_SISTEMA_ERP
	END
GO

CREATE PROCEDURE SP_EXTRAI_DADOS_SISTEMA_ERP
AS
INSERT INTO EXTRACAO_DADOS_SISTEMA
SELECT
A.NUMERO_CONTRATO,
A.DATA_ASSINATURA_CONTRATO,
A.TIPO_FINANCIAMENTO,
A.TAXA_AO_ANO,
A.PZ_FINANCIAMENTO,
A.CIDADE_CLIENTE,
A.ESTADO_CLIENTE,
A.RENDA_MENSAL_CLIENTE,
A.QT_PC_ATRASO,
A.QT_DIAS_PRIM_PC_ATRASO,
A.QT_TOTAL_PC_PAGAS,
A.VL_TOTAL_PC_PAGAS,
A.QT_PC_PAGA_EM_DIA,
A.QT_DIAS_MIN_ATRASO,
A.QT_DIAS_MAX_ATRASO,
A.QT_DIAS_MEDIA_ATRASO,
A.VALOR_FINANCIAMENTO,
A.VALOR_PARCELA,
A.IDADE_DATA_ASSINATURA_CONTRATO,
A.INADIMPLENTE_COBRANCA
FROM SISTEMA_BANCO..CONTRATOS_FINANCIAMENTOS A(NOLOCK)
WHERE NOT EXISTS (SELECT 1 FROM EXTRACAO_DADOS_SISTEMA B(NOLOCK)
						WHERE B.NUMERO_CONTRATO = A.NUMERO_CONTRATO)
GO
/* AGORA PRECISO CRIAR O USU�RIO: user_python SENHA: 123456 PARA TER PERMISS�O PARA LER AS BASES DO BANCO DO SISTEMA ERP
E PARA SER DONO DO BANCO (MODELOS_PREDITIVOS) Al�m disso irei criar um job para que essa tarefa execute diariamente de forma automática*/